const theme = {
  colors: {
    "actionBar.toggledBackground": "#452859",
    "activityBarBadge.background": "#6F44F0",
    "checkbox.border": "#5a5977",
    "editor.background": "#3b224c",
    "editor.foreground": "#ffffff",
    "editor.inactiveSelectionBackground": "#452859",
    "editor.selectionHighlightBackground": "#6F44F026",
    "editorIndentGuide.activeBackground": "#a4a0e8",
    "editorIndentGuide.background": "#5a5977",
    "input.placeholderForeground": "#cccccc",
    "list.activeSelectionIconForeground": "#ffffff",
    "list.dropBackground": "#452859",
    "menu.background": "#281733",
    "menu.border": "#5a5977",
    "menu.foreground": "#cccccc",
    "menu.separatorBackground": "#5a5977",
    "ports.iconRunningProcessForeground": "#9ff28f",
    "sideBarSectionHeader.background": "#00000000",
    "sideBarSectionHeader.border": "#dbbfef33",
    "sideBarTitle.foreground": "#cccccc",
    "statusBarItem.remoteBackground": "#9ff28f",
    "statusBarItem.remoteForeground": "#ffffff",
    "tab.lastPinnedBorder": "#dbbfef33",
    "terminal.inactiveSelectionBackground": "#452859",
    "widget.border": "#5a5977",
  },
  displayName: "helix",
  name: "helix",
  semanticHighlighting: true,
  semanticTokenColors: {
    customLiteral: "#E8DCA0",
    newOperator: "#eccdba",
    numberLiteral: "#E8DCA0",
    stringLiteral: "#cccccc",
  },
  settings: [
    {
      scope: [
        "meta.embedded",
        "source.groovy.embedded",
        "string meta.image.inline.markdown",
        "variable.legacy.builtin.python",
      ],
      settings: { foreground: "#ffffff" },
    },
    { scope: "emphasis", settings: { fontStyle: "italic" } },
    { scope: "strong", settings: { fontStyle: "bold" } },
    { scope: "header", settings: { foreground: "#dbbfef" } },
    { scope: "comment", settings: { foreground: "#697C81" } },
    { scope: "constant.language", settings: { foreground: "#569cd6" } },
    {
      scope: [
        "constant.numeric",
        "variable.other.enummember",
        "keyword.operator.plus.exponent",
        "keyword.operator.minus.exponent",
      ],
      settings: { foreground: "#E8DCA0" },
    },
    { scope: "constant.regexp", settings: { foreground: "#646695" } },
    { scope: "entity.name.tag", settings: { foreground: "#569cd6" } },
    { scope: "entity.name.tag.css", settings: { foreground: "#eccdba" } },
    {
      scope: "entity.other.attribute-name",
      settings: { foreground: "#9ff28f" },
    },
    {
      scope: [
        "entity.other.attribute-name.class.css",
        "entity.other.attribute-name.class.mixin.css",
        "entity.other.attribute-name.id.css",
        "entity.other.attribute-name.parent-selector.css",
        "entity.other.attribute-name.pseudo-class.css",
        "entity.other.attribute-name.pseudo-element.css",
        "source.css.less entity.other.attribute-name.id",
        "entity.other.attribute-name.scss",
      ],
      settings: { foreground: "#eccdba" },
    },
    { scope: "invalid", settings: { foreground: "#f47868" } },
    { scope: "markup.underline", settings: { fontStyle: "underline" } },
    {
      scope: "markup.bold",
      settings: { fontStyle: "bold", foreground: "#eccdba" },
    },
    {
      scope: "markup.heading",
      settings: { fontStyle: "bold", foreground: "lilac" },
    },
    { scope: "markup.italic", settings: { fontStyle: "italic" } },
    {
      scope: "markup.strikethrough",
      settings: { fontStyle: "strikethrough" },
    },
    { scope: "markup.inserted", settings: { foreground: "#E8DCA0" } },
    { scope: "markup.deleted", settings: { foreground: "#cccccc" } },
    { scope: "markup.changed", settings: { foreground: "#eccdba" } },
    {
      scope: "punctuation.definition.quote.begin.markdown",
      settings: { foreground: "#697C81" },
    },
    {
      scope: "punctuation.definition.list.begin.markdown",
      settings: { foreground: "#a4a0e8" },
    },
    { scope: "markup.inline.raw", settings: { foreground: "#cccccc" } },
    {
      scope: "punctuation.definition.tag",
      settings: { foreground: "#5a5977" },
    },
    {
      scope: ["meta.preprocessor", "entity.name.function.preprocessor"],
      settings: { foreground: "#eccdba" },
    },
    {
      scope: "meta.preprocessor.string",
      settings: { foreground: "#cccccc" },
    },
    {
      scope: "meta.preprocessor.numeric",
      settings: { foreground: "#E8DCA0" },
    },
    {
      scope: "meta.structure.dictionary.key.python",
      settings: { foreground: "#9ff28f" },
    },
    { scope: "meta.diff.header", settings: { foreground: "#eccdba" } },
    { scope: "storage", settings: { foreground: "#eccdba" } },
    { scope: "storage.type", settings: { foreground: "#eccdba" } },
    {
      scope: ["storage.modifier", "keyword.operator.noexcept"],
      settings: { foreground: "#eccdba" },
    },
    { scope: "attribute", settings: { foreground: "#dbbfef" } },
    { scope: "keyword", settings: { foreground: "#eccdba" } },
    { scope: "keyword.directive", settings: { foreground: "#dbbfef" } },
    { scope: "namespace", settings: { foreground: "#dbbfef" } },
    { scope: "punctuation", settings: { foreground: "#a4a0e8" } },
    {
      scope: "punctuation.delimiter",
      settings: { foreground: "#a4a0e8" },
    },
    { scope: "operator", settings: { foreground: "#dbbfef" } },
    { scope: "special", settings: { foreground: "#efba5d" } },
    {
      scope: "variable.other.member",
      settings: { foreground: "#ffffff" },
    },
    { scope: "variable", settings: { foreground: "#a4a0e8" } },
    { scope: "variable.parameter", settings: { foreground: "#a4a0e8" } },
    { scope: "variable.builtin", settings: { foreground: "#9ff28f" } },
    { scope: "type", settings: { foreground: "#ffffff" } },
    { scope: "type.builtin", settings: { foreground: "#ffffff" } },
    { scope: "constructor", settings: { foreground: "#dbbfef" } },
    { scope: "function", settings: { foreground: "#ffffff" } },
    { scope: "function.macro", settings: { foreground: "#dbbfef" } },
    { scope: "function.builtin", settings: { foreground: "#ffffff" } },
    { scope: "tag", settings: { foreground: "#eccdba" } },
    { scope: "comment", settings: { foreground: "#697C81" } },
    { scope: "constant", settings: { foreground: "#ffffff" } },
    { scope: "constant.builtin", settings: { foreground: "#ffffff" } },
    { scope: "string", settings: { foreground: "#cccccc" } },
    { scope: "constant.numeric", settings: { foreground: "#E8DCA0" } },
    {
      scope: "constant.character.escape",
      settings: { foreground: "#efba5d" },
    },
    { scope: "label", settings: { foreground: "#efba5d" } },
    { scope: "markup.heading", settings: { foreground: "#dbbfef" } },
    { scope: "markup.bold", settings: { fontStyle: "bold" } },
    { scope: "markup.italic", settings: { fontStyle: "italic" } },
    {
      scope: "markup.strikethrough",
      settings: { fontStyle: "strikethrough" },
    },
    {
      scope: "markup.link.url",
      settings: { foreground: "#cccccc", fontStyle: "underline" },
    },
    { scope: "markup.link.text", settings: { foreground: "#eccdba" } },
    { scope: "markup.raw", settings: { foreground: "#eccdba" } },
    { scope: "diff.plus", settings: { foreground: "#35bf86" } },
    { scope: "diff.minus", settings: { foreground: "#f22c86" } },
    { scope: "diff.delta", settings: { foreground: "#6f44f0" } },
    {
      scope: "diagnostic.hint",
      settings: { fontStyle: "underline", foreground: "#cccccc" },
    },
    {
      scope: "diagnostic.info",
      settings: { fontStyle: "underline", foreground: "#6F44F0" },
    },
    {
      scope: "diagnostic.warning",
      settings: { fontStyle: "underline", foreground: "#ffcd1c" },
    },
    {
      scope: "diagnostic.error",
      settings: { fontStyle: "underline", foreground: "#f47868" },
    },
    { scope: "diagnostic.unnecessary", settings: { fontStyle: "dim" } },
    {
      scope: "diagnostic.deprecated",
      settings: { fontStyle: "strikethrough" },
    },
  ],
};
