# https://ethanschoonover.com/solarized/#usage-development
# https://docs.helix-editor.com/master/themes.html#scopes

"attribute" = { fg = "violet" }

"keyword"           = { fg = "accent", modifiers = ["bold"] }
"keyword.directive" = { fg = "orange" }  # Preprocessor directives (`#if` in C)

"module"    = { fg = "violet" }
"namespace" = { fg = "violet" }
"operator"  = { fg = "green" }
"special"   = { fg = "orange" }

"type"         = { fg = "yellow" }
"type.builtin" = { fg = "yellow", modifiers = ["bold"] }

"variable"          = "primary"
"variable.builtin"  = { fg = "cyan", modifiers = ["bold"] }
"variable.function" = { fg = "blue" }

"constant"                  = { fg = "cyan" }
"constant.builtin"          = { fg = "cyan", modifiers = ["bold"] }
"constant.character.escape" = { fg = "red", modifiers = ["bold"] }

"function"         = { fg = "blue" }
"function.macro"   = { fg = "magenta" }
"function.builtin" = { fg = "blue", modifiers = ["bold"] }
"function.special" = { fg = "magenta" }

"string"      = "cyan"
"constructor" = "blue"
"comment"     = "secondary"
"label"       = "green"
"tag"         = "magenta"

"punctuation"         = "primary"
"punctuation.special" = { fg = "magenta", modifiers = ["bold"] }

"markup.heading"       = "blue"
"markup.list"          = "red"
"markup.bold"          = { fg = "yellow", modifiers = ["bold"] }
"markup.italic"        = { fg = "magenta", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url"      = { fg = "yellow", modifiers = ["underlined"] }
"markup.link.text"     = "red"
"markup.quote"         = "cyan"
"markup.raw"           = "green"

"diff.minus" = { fg = "red" }
"diff.plus"  = { fg = "light_green" }
"diff.delta" = { fg = "light_yellow" }

"ui.background" = { fg = "primary", bg = "background" }

# line number
"ui.linenr"          = { fg = "secondary" }
"ui.linenr.selected" = { fg = "blue", modifiers = ["bold"] }

"ui.bufferline"        = { fg = "secondary", bg = "bg_highlight" }
"ui.bufferline.active" = { fg = "background", bg = "accent", modifiers = [
  "bold"
] }

"ui.statusline"          = { fg = "background", bg = "primary" }
"ui.statusline.inactive" = { fg = "bg_highlight", bg = "secondary" }
"ui.statusline.normal"   = { bg = "blue", modifiers = ["bold"] }
"ui.statusline.insert"   = { bg = "light_green", modifiers = ["bold"] }
"ui.statusline.select"   = { bg = "magenta", modifiers = ["bold"] }

# Vertical window separator style
"ui.window" = { fg = "secondary" }
"ui.popup"  = { fg = "accent", bg = "bg_highlight" }
"ui.help"   = { fg = "primary", bg = "bg_highlight" }

"ui.menu"          = { fg = "primary", bg = "bg_highlight" }
"ui.menu.selected" = { fg = "violet", bg = "selection", modifiers = ["bold"] }

"ui.text"           = { fg = "accent" }
"ui.text.focus"     = { fg = "violet", bg = "selection", modifiers = ["bold"] }
"ui.text.inactive"  = { fg = "secondary" }
"ui.text.directory" = { fg = "blue" }

# "ui.cursor"         = { fg = "background", bg = "cyan" }
# "ui.cursor.primary" = { fg = "background", bg = "accent" }
"ui.cursor.match" = { fg = "magenta", bg = "selection", modifiers = [
  "bold",
  "underlined"
] }

"ui.cursor.primary.normal" = { fg = "background", bg = "accent" }
"ui.cursor.primary.insert" = { fg = "background", bg = "light_green" }
"ui.cursor.primary.select" = { fg = "background", bg = "magenta" }
"ui.cursor.normal"         = { fg = "background", bg = "cyan" }
"ui.cursor.insert"         = { fg = "background", bg = "green" }
"ui.cursor.select"         = { fg = "background", bg = "violet" }

"ui.cursorline"           = { bg = "bg_highlight" }
"ui.cursorline.secondary" = { bg = "bg_highlight_secondary" }

"ui.selection"         = { bg = "selection_secondary" }
"ui.selection.primary" = { bg = "selection" }

"ui.virtual.indent-guide" = { fg = "bg_highlight" }
"ui.virtual.ruler"        = { bg = "bg_highlight_secondary" }
"ui.virtual.whitespace"   = { fg = "secondary" }
"ui.virtual.inlay-hint"   = { fg = "secondary", bg = "bg_highlight_secondary", modifiers = [
  "italic"
] }
"ui.virtual.jump-label"   = { fg = "red", modifiers = ["bold"] }

"warning" = { fg = "yellow" }
"error"   = { fg = "red" }
"info"    = { fg = "blue" }
"hint"    = { fg = "green" }

"diagnostic.warning"     = { underline = { style = "curl", color = "yellow" } }
"diagnostic.error"       = { underline = { style = "curl", color = "red" } }
"diagnostic.info"        = { underline = { style = "curl", color = "blue" } }
"diagnostic.hint"        = { underline = { style = "curl", color = "green" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated"  = { modifiers = ["crossed_out"] }

[palette]
accent                 = "#586e75"  # base01
primary                = "#657b83"  # base00
secondary              = "#93a1a1"  # base1
bg_highlight           = "#eee8d5"  # base2
bg_highlight_secondary = "#f5eedb"
background             = "#fdf6e3"  # base3
selection              = "#c5c8bd"
selection_secondary    = "#dddbcc"

red          = "#dc322f"
green        = "#859900"
light_green  = "#00AB6A"
yellow       = "#b58900"
light_yellow = "#C49A00"
blue         = "#268bd2"
magenta      = "#d33682"
cyan         = "#2aa198"
orange       = "#cb4b16"
violet       = "#6c71c4"

# base03 = "#002b36"  # brblack
# base02 = "#073642"  # black
# base01 = "#586e75"  # dimgray
# base00 = "#657b83"  # mutedgray
# base0  = "#839496"  # gray
# base1  = "#93a1a1"  # brgray
# base2  = "#eee8d5"  # white
# base3  = "#fdf6e3"  # brwhite
