inherits = "solarized_light"

[palette]
accent                 = "#93a1a1"  # base1
primary                = "#839496"  # base0
secondary              = "#586e75"  # base01
bg_highlight           = "#073642"  # base02
bg_highlight_secondary = "#03303b"
background             = "#002b36"  # base03
selection              = "#2c4f59"
selection_secondary    = "#16404b"
