# Author: IwantHappiness <IwantHappiness95@gmail.com>

inherits = "vesper"

"markup.raw" = { bg = "white" }
"markup.normal" = { bg = "white" }
"markup.heading" = { bg = "white" }

# UI
"ui.window" = { bg = "white" }
"ui.background" = { fg = "white" }

[palette]
red = "#ff8080"
gray = "#A0A0A0"
white = "#ffffff"
beige = "#ffc799"
black = "#101010"
dim-gray = "#505050"
dark-gray = "#1C1C1C"
bright-green = "#99FFE4"

cursor = "#aeafad"
comment = "#8b8b8b"
bg-selection = "#666666"
