(assignment (NAME) @local.definition.variable)
(alias left:(NAME) @local.definition.variable)
(alias right:(NAME) @local.reference.variable)
(value (NAME) @local.reference.variable)
(parameter (NAME) @local.definition.variable)

(call (NAME) @local.reference.function)
(dependency (NAME) @local.reference.function)
(depcall (NAME) @local.reference.function)
(recipeheader (NAME) @local.definition.function)
