; Scopes

[
  (source_file)
  (body)
  (body_expression)
] @local.scope

; Definitions

(package name: (_) @local.definition.namespace)
(library_package name: (_) @local.definition.namespace)
(namespace name: (_) @local.definition.namespace)
(part_definition name: (_) @local.definition.type)
(item_definition name: (_) @local.definition.type)
(attribute_definition name: (_) @local.definition.type)
(enumeration_definition name: (_) @local.definition.type)
(occurrence_definition name: (_) @local.definition.type)
(port_definition name: (_) @local.definition.type)
(connection_definition name: (_) @local.definition.type)
(interface_definition name: (_) @local.definition.type)
(allocation_definition name: (_) @local.definition.type)
(flow_definition name: (_) @local.definition.type)
(metadata_definition name: (_) @local.definition.type)
(extended_definition name: (_) @local.definition.type)
(state_definition name: (_) @local.definition.type)
(constraint_definition name: (_) @local.definition.type)
(requirement_definition name: (_) @local.definition.type)
(concern_definition name: (_) @local.definition.type)
(case_definition name: (_) @local.definition.type)
(analysis_case_definition name: (_) @local.definition.type)
(verification_case_definition name: (_) @local.definition.type)
(use_case_definition name: (_) @local.definition.type)
(view_definition name: (_) @local.definition.type)
(viewpoint_definition name: (_) @local.definition.type)
(rendering_definition name: (_) @local.definition.type)

(action_definition name: (_) @local.definition.function)
(calculation_definition name: (_) @local.definition.function)
(action_usage name: (_) @local.definition.function)
(calculation_usage name: (_) @local.definition.function)
(perform_action_usage name: (_) @local.definition.function)
(constraint_usage name: (_) @local.definition.function)
(assert_constraint_usage name: (_) @local.definition.function)
(requirement_constraint_usage name: (_) @local.definition.function)
(state_usage name: (_) @local.definition.label)
(exhibit_state_usage name: (_) @local.definition.label)
(transition_usage name: (_) @local.definition.label)

(part_usage name: (_) @local.definition.variable)
(item_usage name: (_) @local.definition.variable)
(attribute_usage name: (_) @local.definition.variable)
(reference_usage name: (_) @local.definition.variable)
(enumeration_usage name: (_) @local.definition.constant)
(occurrence_usage name: (_) @local.definition.variable)
(port_usage name: (_) @local.definition.variable)
(connection_usage name: (_) @local.definition.variable)
(interface_usage name: (_) @local.definition.variable)
(allocation_usage name: (_) @local.definition.variable)
(flow_usage name: (_) @local.definition.variable)
(metadata_usage name: (_) @local.definition.variable)
(requirement_usage name: (_) @local.definition.variable)
(concern_usage name: (_) @local.definition.variable)
(case_usage name: (_) @local.definition.variable)
(analysis_case_usage name: (_) @local.definition.variable)
(verification_case_usage name: (_) @local.definition.variable)
(use_case_usage name: (_) @local.definition.variable)
(view_usage name: (_) @local.definition.variable)
(viewpoint_usage name: (_) @local.definition.variable)
(rendering_usage name: (_) @local.definition.variable)
(event_occurrence_usage name: (_) @local.definition.variable)
(subject_usage name: (_) @local.definition.variable)
(actor_usage name: (_) @local.definition.variable)
(stakeholder_usage name: (_) @local.definition.variable)
(for_variable name: (_) @local.definition.variable)
(alias_member name: (_) @local.definition.namespace)

; References

(qualified_name [(identifier) (unrestricted_name)] @local.reference)

; Named arguments are parameter names, not variable references.
(named_argument name: (qualified_name [(identifier) (unrestricted_name)] @_))
