;; Auto-generated by tenzir/tree-sitter-tql/scripts/generate-highlights.mjs. DO NOT EDIT.

[
  "let"
  "if"
  "else"
  "match"
  "and"
  "or"
  "not"
  "move"
  "in"
  "this"
  "?"
  "."
  "..."
  "["
  "]"
  "{"
  "}"
  ":"
] @keyword

[
  "+"
  "-"
  "*"
  "/"
] @keyword

"_" @variable.builtin

"null" @constant.builtin

[
  "true"
  "false"
] @boolean

(dollar_var) @variable.builtin
(global_sigil) @keyword
(metadata_sigil) @keyword
(meta_selector) @attribute
(number) @number
(string) @string
(format_expr) @string
(ip) @constant
(subnet) @constant
(time) @number
(duration) @number
(frontmatter_open) @comment
(frontmatter_close) @comment
(comment) @comment

(invocation
  operator: (entity) @function.call)
(call_expression
  (entity) @function.call)
(call_expression
  method: (entity) @function.method)
((identifier) @variable.builtin (#match? @variable.builtin "^\$[A-Za-z_]\w*$"))

[
  "("
  ")"
] @punctuation.bracket

[
  ","
] @punctuation.delimiter

[
  "="
  "=>"
  "|"
  "::"
  "=="
  "!="
  ">"
  ">="
  "<"
  "<="
] @operator
