;; Auto-generated by tenzir/tree-sitter-tql/scripts/generate-indents.mjs. DO NOT EDIT.

[
  (then_block)
  (else_block)
  (pipeline_block)
  (match_statement)
  (match_arm)
  (list)
  (record)
] @indent

[
  "}"
  "]"
] @outdent
