([(show_expression) (set_expression)] @constant)
([(line_comment) (block_comment)] @comment)
((identifier) @function)
((string_literal) @string)
((asssigned_argument) @type)
(["#"] @punctuation)
(["+"] @operator)
(["(" ")" "{" "}" "[" "]"] @punctuation.brackets)
(["="] @markup.heading)
